//! Project context scanner: produces AGENTS.md describing the codebase.

use std::path::{Path, PathBuf};
use std::collections::HashMap;
use std::cmp::Reverse;

/// Summary of a project's structure.
#[derive(Debug, Default)]
pub struct ProjectContext {
    pub name:        String,
    pub root:        PathBuf,
    pub languages:   HashMap<String, usize>, // extension → file count
    pub top_files:   Vec<PathBuf>,           // up to 20 notable files
    pub has_git:     bool,
    pub readme:      Option<String>,
    pub cargo_toml:  Option<String>,
    pub package_json: Option<String>,
}

impl ProjectContext {
    /// Scan the project at `root` and return a context summary.
    pub fn scan(root: &Path) -> Self {
        let mut ctx = ProjectContext {
            root:   root.to_path_buf(),
            name:   root.file_name().map(|n| n.to_string_lossy().into_owned())
                        .unwrap_or_else(|| "project".into()),
            has_git: root.join(".git").exists(),
            ..Default::default()
        };

        // Read README and manifest files
        for candidate in &["README.md", "README.txt", "README.rst", "README"] {
            let p = root.join(candidate);
            if let Ok(s) = std::fs::read_to_string(&p) {
                ctx.readme = Some(s.chars().take(2000).collect());
                break;
            }
        }
        ctx.cargo_toml   = std::fs::read_to_string(root.join("Cargo.toml")).ok();
        ctx.package_json = std::fs::read_to_string(root.join("package.json")).ok();

        // Walk directory tree
        let mut notable: Vec<(PathBuf, u64)> = Vec::new();
        walk(root, &mut ctx.languages, &mut notable, 0);

        // Sort by size desc, take top 20
        notable.sort_by_key(|a| Reverse(a.1));
        ctx.top_files = notable.into_iter().take(20).map(|(p, _)| p).collect();

        ctx
    }

    /// Generate the contents of an AGENTS.md file.
    pub fn to_agents_md(&self) -> String {
        let mut md = String::new();

        md.push_str(&format!("# AGENTS.md — {}\n\n", self.name));
        md.push_str("This file was generated by Quark Code's `/init` command.\n\n");

        // Languages
        let mut langs: Vec<(&String, &usize)> = self.languages.iter().collect();
        langs.sort_by(|a, b| b.1.cmp(a.1));
        if !langs.is_empty() {
            md.push_str("## Languages\n\n");
            for (ext, count) in langs.iter().take(10) {
                md.push_str(&format!("- `.{ext}` — {count} files\n"));
            }
            md.push('\n');
        }

        // Build system
        md.push_str("## Build / Package Manager\n\n");
        if self.cargo_toml.is_some() {
            md.push_str("- **Rust** (Cargo)\n");
        }
        if self.package_json.is_some() {
            md.push_str("- **Node.js** (npm/yarn/pnpm)\n");
        }
        md.push('\n');

        // Key files
        if !self.top_files.is_empty() {
            md.push_str("## Notable Files\n\n");
            for f in &self.top_files {
                let rel = f.strip_prefix(&self.root).unwrap_or(f);
                md.push_str(&format!("- `{}`\n", rel.display()));
            }
            md.push('\n');
        }

        // README summary
        if let Some(readme) = &self.readme {
            md.push_str("## README Summary\n\n");
            let preview: String = readme.lines().take(15).collect::<Vec<_>>().join("\n");
            md.push_str(&format!("```\n{preview}\n```\n\n"));
        }

        // Git
        if self.has_git {
            md.push_str("## VCS\n\nGit repository detected.\n\n");
        }

        md.push_str("## Agent Instructions\n\n");
        md.push_str("- Always read relevant files before making changes.\n");
        md.push_str("- In Plan mode, only suggest changes — do not apply them.\n");
        md.push_str("- In Build mode, apply changes using `write_file` or `write_lines`.\n");
        md.push_str("- Use `git_status` to check for uncommitted changes before editing.\n");
        md.push_str("- Prefer small, focused edits over large rewrites.\n");
        md.push_str("- After making changes, summarise what was done.\n");

        md
    }
}

fn walk(
    dir:   &Path,
    langs: &mut HashMap<String, usize>,
    files: &mut Vec<(PathBuf, u64)>,
    depth: usize,
) {
    if depth > 6 { return; }
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
            if name.starts_with('.') || matches!(name, "target" | "node_modules" | "dist" | "build") {
                continue;
            }
        }
        if path.is_dir() {
            walk(&path, langs, files, depth + 1);
        } else {
            let ext = path.extension()
                .and_then(|e| e.to_str())
                .unwrap_or("")
                .to_lowercase();
            if !ext.is_empty() {
                *langs.entry(ext.clone()).or_insert(0) += 1;
            }
            let size = std::fs::metadata(&path).map(|m| m.len()).unwrap_or(0);
            // Only track source files
            if matches!(ext.as_str(),
                "rs" | "py" | "ts" | "js" | "tsx" | "jsx" | "go" | "java" |
                "c" | "cpp" | "h" | "hpp" | "cs" | "rb" | "swift" | "kt" | "toml" | "json"
            ) {
                files.push((path, size));
            }
        }
    }
}
